api:
<<<<<<< HEAD
  instanceid: "20654378"
 
tls:
  alias: "mule"
  keyPassword: "password"
  password: "password"
  path: "keystore.jks"

http:
  port: "8081"
=======
  instanceid: "api-manager-instance-id"

tls:
  alias: "keystore-alias"
  keyPassword: "keystore-key-password"
  password: "keystore-password"
  path: "keystore-file-name"

http:
  port: "https-listener-port"
>>>>>>> branch 'master' of https://github.com/gsadanalamss/vehicle-data.git
